/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./database.types";

export const publicAccGroupUserStatusSchema = z.enum([
  "invited",
  "accepted",
  "rejected",
  "owner",
]);

export const publicAccTransactionSplitTypeSchema = z.enum([
  "equal",
  "shares",
  "manual",
  "percentage",
]);

export const publicDrinktypeSchema = z.enum(["beer"]);

export const publicTextDocumentTypeSchema = z.enum([
  "bio",
  "blog",
  "trip_post",
  "trip_description",
]);

export const publicTextdocumentaccessSchema = z.enum(["open", "restricted"]);

export const publicTextdocumentstatusSchema = z.enum([
  "draft",
  "published",
  "unpublished",
]);

export const publicTrackergamestatusSchema = z.enum([
  "paused",
  "active",
  "finished",
]);

export const publicTransactionStatusSchema = z.enum([
  "idea",
  "quoted",
  "committed",
  "paid",
]);

export const publicTripFeedItemTypeSchema = z.enum(["post", "announcement"]);

export const publicTripParticipantRoleSchema = z.enum([
  "admin",
  "member",
  "owner",
]);

export const publicTripParticipantStatusSchema = z.enum([
  "invited",
  "declined",
  "confirmed",
  "tentative",
]);

export const publicTripStatusSchema = z.enum([
  "proposed",
  "confirmed",
  "cancelled",
  "past",
]);

export const publicTripTransactionCalculationTypeSchema = z.enum([
  "group_total",
  "per_day",
  "per_participant",
  "per_participant_per_day",
]);

export const publicTripTransactionCategorySchema = z.enum([
  "food",
  "transport",
  "fuel",
  "stay",
  "activity",
  "other",
]);

export const publicTripTypesSchema = z.enum([
  "citybreak",
  "sailing",
  "skiing",
  "caravaning",
  "hiking",
  "cayaking",
  "other",
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAccommodationRowSchema = z.object({
  check_in_date: z.string(),
  check_out_date: z.string(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  name: z.string(),
  status: publicTripStatusSchema,
  stay_duration_days: z.number().nullable(),
  trip_id: z.string(),
});

export const publicAccommodationInsertSchema = z.object({
  check_in_date: z.string(),
  check_out_date: z.string(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  name: z.string(),
  status: publicTripStatusSchema.optional(),
  stay_duration_days: z.number().optional().nullable(),
  trip_id: z.string(),
});

export const publicAccommodationUpdateSchema = z.object({
  check_in_date: z.string().optional(),
  check_out_date: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  name: z.string().optional(),
  status: publicTripStatusSchema.optional(),
  stay_duration_days: z.number().optional().nullable(),
  trip_id: z.string().optional(),
});

export const publicAccommodationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicAccommodationUnitRowSchema = z.object({
  accommodation_id: z.string(),
  assigned_participants: z.number(),
  capacity: z.number().nullable(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  id: z.string(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  name: z.string(),
});

export const publicAccommodationUnitInsertSchema = z.object({
  accommodation_id: z.string(),
  assigned_participants: z.number().optional(),
  capacity: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  name: z.string(),
});

export const publicAccommodationUnitUpdateSchema = z.object({
  accommodation_id: z.string().optional(),
  assigned_participants: z.number().optional(),
  capacity: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  name: z.string().optional(),
});

export const publicAccommodationUnitRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("accommodation_unit_accommodation_id_fkey"),
    columns: z.tuple([z.literal("accommodation_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("accommodation"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("accommodation_unit_accommodation_id_fkey"),
    columns: z.tuple([z.literal("accommodation_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_accommodation_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicAccommodationUnitAssignmentRowSchema = z.object({
  accommodation_unit_id: z.string(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  trip_participant_id: z.string(),
});

export const publicAccommodationUnitAssignmentInsertSchema = z.object({
  accommodation_unit_id: z.string(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  trip_participant_id: z.string(),
});

export const publicAccommodationUnitAssignmentUpdateSchema = z.object({
  accommodation_unit_id: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  trip_participant_id: z.string().optional(),
});

export const publicAccommodationUnitAssignmentRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "accommodation_unit_assignment_accommodation_unit_id_fkey",
    ),
    columns: z.tuple([z.literal("accommodation_unit_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("accommodation_unit"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal(
      "accommodation_unit_assignment_trip_participant_id_fkey",
    ),
    columns: z.tuple([z.literal("trip_participant_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip_participant"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal(
      "accommodation_unit_assignment_trip_participant_id_fkey",
    ),
    columns: z.tuple([z.literal("trip_participant_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal(
      "accommodation_unit_assignment_trip_participant_id_fkey",
    ),
    columns: z.tuple([z.literal("trip_participant_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBalanceRowSchema = z.object({
  borrower_id: z.string(),
  created_at: z.string(),
  currency_balance: jsonSchema,
  lender_id: z.string(),
});

export const publicBalanceInsertSchema = z.object({
  borrower_id: z.string(),
  created_at: z.string().optional(),
  currency_balance: jsonSchema.optional(),
  lender_id: z.string(),
});

export const publicBalanceUpdateSchema = z.object({
  borrower_id: z.string().optional(),
  created_at: z.string().optional(),
  currency_balance: jsonSchema.optional(),
  lender_id: z.string().optional(),
});

export const publicBalanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicConsumedDrinkRowSchema = z.object({
  created_at: z.string(),
  drank_at: z.string(),
  drink_type: publicDrinktypeSchema,
  id: z.string(),
  quantity: z.number(),
  user_id: z.string(),
});

export const publicConsumedDrinkInsertSchema = z.object({
  created_at: z.string().optional(),
  drank_at: z.string(),
  drink_type: publicDrinktypeSchema.optional(),
  id: z.string().optional(),
  quantity: z.number(),
  user_id: z.string(),
});

export const publicConsumedDrinkUpdateSchema = z.object({
  created_at: z.string().optional(),
  drank_at: z.string().optional(),
  drink_type: publicDrinktypeSchema.optional(),
  id: z.string().optional(),
  quantity: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicConsumedDrinkRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("consumed_drink_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("consumed_drink_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("consumed_drink_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicGamescoreRowSchema = z.object({
  createdAt: z.string(),
  finishedAt: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  ownerId: z.string(),
  status: z.string(),
});

export const publicGamescoreInsertSchema = z.object({
  createdAt: z.string().optional(),
  finishedAt: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  ownerId: z.string(),
  status: z.string().optional(),
});

export const publicGamescoreUpdateSchema = z.object({
  createdAt: z.string().optional(),
  finishedAt: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  ownerId: z.string().optional(),
  status: z.string().optional(),
});

export const publicGroupRowSchema = z.object({
  archived_at: z.string().nullable(),
  created_at: z.string(),
  currencies: jsonSchema,
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  owner_id: z.string(),
  thumbnail_url: z.string().nullable(),
});

export const publicGroupInsertSchema = z.object({
  archived_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  currencies: jsonSchema.optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  owner_id: z.string().optional(),
  thumbnail_url: z.string().optional().nullable(),
});

export const publicGroupUpdateSchema = z.object({
  archived_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  currencies: jsonSchema.optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  owner_id: z.string().optional(),
  thumbnail_url: z.string().optional().nullable(),
});

export const publicGroupRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicGroupBalanceRowSchema = z.object({
  borrower_id: z.string(),
  currency_balance: jsonSchema,
  group_id: z.string(),
  lender_id: z.string(),
  updated_at: z.string(),
});

export const publicGroupBalanceInsertSchema = z.object({
  borrower_id: z.string(),
  currency_balance: jsonSchema.optional(),
  group_id: z.string(),
  lender_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicGroupBalanceUpdateSchema = z.object({
  borrower_id: z.string().optional(),
  currency_balance: jsonSchema.optional(),
  group_id: z.string().optional(),
  lender_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicGroupBalanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_balance_lender_id_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
]);

export const publicGroupInvitationRowSchema = z.object({
  accepted_at: z.string().nullable(),
  created_at: z.string(),
  group_id: z.string(),
  group_member_id: z.string(),
  rejected_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicGroupInvitationInsertSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  created_at: z.string(),
  group_id: z.string(),
  group_member_id: z.string(),
  rejected_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicGroupInvitationUpdateSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  group_id: z.string().optional(),
  group_member_id: z.string().optional(),
  rejected_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicGroupInvitationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_invitation_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicGroupMemberRowSchema = z.object({
  added_at: z.string(),
  assigned_at: z.string().nullable(),
  group_id: z.string(),
  id: z.string(),
  nickname: z.string(),
  removed_at: z.string().nullable(),
  status: publicAccGroupUserStatusSchema.nullable(),
  user_id: z.string().nullable(),
});

export const publicGroupMemberInsertSchema = z.object({
  added_at: z.string(),
  assigned_at: z.string().optional().nullable(),
  group_id: z.string(),
  id: z.string().optional(),
  nickname: z.string(),
  removed_at: z.string().optional().nullable(),
  status: publicAccGroupUserStatusSchema.optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicGroupMemberUpdateSchema = z.object({
  added_at: z.string().optional(),
  assigned_at: z.string().optional().nullable(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  nickname: z.string().optional(),
  removed_at: z.string().optional().nullable(),
  status: publicAccGroupUserStatusSchema.optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicGroupMemberRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_member_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicPiwoPaliwoMemberRowSchema = z.object({
  bio: z.string().nullable(),
  education: z.array(z.string()).nullable(),
  fav_beer: z.string().nullable(),
  first_name: z.string(),
  id: z.string(),
  image_url: z.string().nullable(),
  location: z.string().nullable(),
  nickname: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const publicPiwoPaliwoMemberInsertSchema = z.object({
  bio: z.string().optional().nullable(),
  education: z.array(z.string()).optional().nullable(),
  fav_beer: z.string().optional().nullable(),
  first_name: z.string(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  nickname: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicPiwoPaliwoMemberUpdateSchema = z.object({
  bio: z.string().optional().nullable(),
  education: z.array(z.string()).optional().nullable(),
  fav_beer: z.string().optional().nullable(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  nickname: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicPiwoPaliwoMemberRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("piwo_paliwo_member_bio_fkey"),
    columns: z.tuple([z.literal("bio")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocument"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTextdocumentRowSchema = z.object({
  access: publicTextdocumentaccessSchema,
  author: z.string(),
  banner_url: z.string().nullable(),
  created_at: z.string(),
  document_type: publicTextDocumentTypeSchema.nullable(),
  id: z.string(),
  markdown: z.string().nullable(),
  status: publicTextdocumentstatusSchema,
  thumbnail_url: z.string().nullable(),
  title: z.string().nullable(),
});

export const publicTextdocumentInsertSchema = z.object({
  access: publicTextdocumentaccessSchema.optional(),
  author: z.string().optional(),
  banner_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  document_type: publicTextDocumentTypeSchema.optional().nullable(),
  id: z.string().optional(),
  markdown: z.string().optional().nullable(),
  status: publicTextdocumentstatusSchema.optional(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
});

export const publicTextdocumentUpdateSchema = z.object({
  access: publicTextdocumentaccessSchema.optional(),
  author: z.string().optional(),
  banner_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  document_type: publicTextDocumentTypeSchema.optional().nullable(),
  id: z.string().optional(),
  markdown: z.string().optional().nullable(),
  status: publicTextdocumentstatusSchema.optional(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
});

export const publicTextdocumentRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("TextDocument_author_fkey1"),
    columns: z.tuple([z.literal("author")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("TextDocument_author_fkey1"),
    columns: z.tuple([z.literal("author")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("TextDocument_author_fkey1"),
    columns: z.tuple([z.literal("author")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicTextdocumentcommentRowSchema = z.object({
  author_id: z.string(),
  id: z.string(),
  responding_to_comment_id: z.string().nullable(),
  text: z.string().nullable(),
  text_document_id: z.string(),
  time: z.string(),
});

export const publicTextdocumentcommentInsertSchema = z.object({
  author_id: z.string(),
  id: z.string().optional(),
  responding_to_comment_id: z.string().optional().nullable(),
  text: z.string().optional().nullable(),
  text_document_id: z.string(),
  time: z.string().optional(),
});

export const publicTextdocumentcommentUpdateSchema = z.object({
  author_id: z.string().optional(),
  id: z.string().optional(),
  responding_to_comment_id: z.string().optional().nullable(),
  text: z.string().optional().nullable(),
  text_document_id: z.string().optional(),
  time: z.string().optional(),
});

export const publicTextdocumentcommentRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("TextDocumentComment_author_id_fkey"),
    columns: z.tuple([z.literal("author_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("TextDocumentComment_author_id_fkey"),
    columns: z.tuple([z.literal("author_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("TextDocumentComment_author_id_fkey"),
    columns: z.tuple([z.literal("author_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal(
      "TextDocumentComment_responding_to_comment_id_fkey",
    ),
    columns: z.tuple([z.literal("responding_to_comment_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocumentComment"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("TextDocumentComment_text_document_id_fkey"),
    columns: z.tuple([z.literal("text_document_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocument"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTransactionRowSchema = z.object({
  amount: z.number(),
  created_at: z.string(),
  currency_iso_code: z.string(),
  description: z.string().nullable(),
  group_id: z.string(),
  id: z.string(),
  paid_by_id: z.string(),
  split_type: publicAccTransactionSplitTypeSchema,
});

export const publicTransactionInsertSchema = z.object({
  amount: z.number(),
  created_at: z.string().optional(),
  currency_iso_code: z.string().optional(),
  description: z.string().optional().nullable(),
  group_id: z.string(),
  id: z.string().optional(),
  paid_by_id: z.string(),
  split_type: publicAccTransactionSplitTypeSchema.optional(),
});

export const publicTransactionUpdateSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  currency_iso_code: z.string().optional(),
  description: z.string().optional().nullable(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  paid_by_id: z.string().optional(),
  split_type: publicAccTransactionSplitTypeSchema.optional(),
});

export const publicTransactionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("paid_by_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("paid_by_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("paid_by_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("paid_by_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
]);

export const publicTransactionSplitRowSchema = z.object({
  amount: z.number(),
  balance_id: z.string().nullable(),
  borrower_id: z.string(),
  created_at: z.string(),
  group_id: z.string(),
  transaction_id: z.string(),
});

export const publicTransactionSplitInsertSchema = z.object({
  amount: z.number(),
  balance_id: z.string().optional().nullable(),
  borrower_id: z.string(),
  created_at: z.string().optional(),
  group_id: z.string(),
  transaction_id: z.string(),
});

export const publicTransactionSplitUpdateSchema = z.object({
  amount: z.number().optional(),
  balance_id: z.string().optional().nullable(),
  borrower_id: z.string().optional(),
  created_at: z.string().optional(),
  group_id: z.string().optional(),
  transaction_id: z.string().optional(),
});

export const publicTransactionSplitRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_transaction_id_fkey"),
    columns: z.tuple([z.literal("transaction_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("transaction"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTripRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string().nullable(),
  currency_iso_code: z.string(),
  description: z.string().nullable(),
  end_date: z.string(),
  group_id: z.string(),
  id: z.string(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  location: z.string().nullable(),
  name: z.string(),
  start_date: z.string(),
  status: publicTripStatusSchema,
  text_document_id: z.string().nullable(),
  type: publicTripTypesSchema,
});

export const publicTripInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  currency_iso_code: z.string(),
  description: z.string().optional().nullable(),
  end_date: z.string(),
  group_id: z.string(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  name: z.string(),
  start_date: z.string(),
  status: publicTripStatusSchema.optional(),
  text_document_id: z.string().optional().nullable(),
  type: publicTripTypesSchema.optional(),
});

export const publicTripUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  currency_iso_code: z.string().optional(),
  description: z.string().optional().nullable(),
  end_date: z.string().optional(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  name: z.string().optional(),
  start_date: z.string().optional(),
  status: publicTripStatusSchema.optional(),
  text_document_id: z.string().optional().nullable(),
  type: publicTripTypesSchema.optional(),
});

export const publicTripRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_text_document_id_fkey"),
    columns: z.tuple([z.literal("text_document_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocument"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTripFeedItemRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  id: z.number(),
  last_modified_at: z.string(),
  last_modified_by: z.string(),
  text_document_id: z.string(),
  trip_id: z.string(),
  type: publicTripFeedItemTypeSchema,
});

export const publicTripFeedItemInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  id: z.number().optional(),
  last_modified_at: z.string(),
  last_modified_by: z.string(),
  text_document_id: z.string(),
  trip_id: z.string(),
  type: publicTripFeedItemTypeSchema.optional(),
});

export const publicTripFeedItemUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  id: z.number().optional(),
  last_modified_at: z.string().optional(),
  last_modified_by: z.string().optional(),
  text_document_id: z.string().optional(),
  trip_id: z.string().optional(),
  type: publicTripFeedItemTypeSchema.optional(),
});

export const publicTripFeedItemRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_feed_item_text_document_id_fkey"),
    columns: z.tuple([z.literal("text_document_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocument"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_feed_item_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_feed_item_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_feed_item_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicTripParticipantRowSchema = z.object({
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  group_member_id: z.string(),
  id: z.string(),
  is_confirmed: z.boolean().nullable(),
  is_declined: z.boolean().nullable(),
  is_tentative: z.boolean().nullable(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  role: publicTripParticipantRoleSchema,
  status: publicTripParticipantStatusSchema,
  trip_id: z.string(),
});

export const publicTripParticipantInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  group_member_id: z.string(),
  id: z.string().optional(),
  is_confirmed: z.boolean().optional().nullable(),
  is_declined: z.boolean().optional().nullable(),
  is_tentative: z.boolean().optional().nullable(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  role: publicTripParticipantRoleSchema.optional(),
  status: publicTripParticipantStatusSchema.optional(),
  trip_id: z.string(),
});

export const publicTripParticipantUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  group_member_id: z.string().optional(),
  id: z.string().optional(),
  is_confirmed: z.boolean().optional().nullable(),
  is_declined: z.boolean().optional().nullable(),
  is_tentative: z.boolean().optional().nullable(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  role: publicTripParticipantRoleSchema.optional(),
  status: publicTripParticipantStatusSchema.optional(),
  trip_id: z.string().optional(),
});

export const publicTripParticipantRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_participant_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicTripTransactionRowSchema = z.object({
  amount: z.number(),
  calculation_type: publicTripTransactionCalculationTypeSchema,
  category: publicTripTransactionCategorySchema,
  created_at: z.string(),
  created_by: z.string().nullable(),
  currency_iso_code: z.string(),
  description: z.string(),
  group_id: z.string(),
  id: z.string(),
  last_modified_at: z.string().nullable(),
  last_modified_by: z.string().nullable(),
  notes: z.string().nullable(),
  split_type: publicAccTransactionSplitTypeSchema,
  status: publicTransactionStatusSchema,
  total_amount: z.number().nullable(),
  transaction_split: jsonSchema,
  trip_id: z.string(),
});

export const publicTripTransactionInsertSchema = z.object({
  amount: z.number().optional(),
  calculation_type: publicTripTransactionCalculationTypeSchema.optional(),
  category: publicTripTransactionCategorySchema,
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  currency_iso_code: z.string().optional(),
  description: z.string(),
  group_id: z.string(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  split_type: publicAccTransactionSplitTypeSchema.optional(),
  status: publicTransactionStatusSchema.optional(),
  total_amount: z.number().optional().nullable(),
  transaction_split: jsonSchema.optional(),
  trip_id: z.string(),
});

export const publicTripTransactionUpdateSchema = z.object({
  amount: z.number().optional(),
  calculation_type: publicTripTransactionCalculationTypeSchema.optional(),
  category: publicTripTransactionCategorySchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  currency_iso_code: z.string().optional(),
  description: z.string().optional(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  last_modified_at: z.string().optional().nullable(),
  last_modified_by: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  split_type: publicAccTransactionSplitTypeSchema.optional(),
  status: publicTransactionStatusSchema.optional(),
  total_amount: z.number().optional().nullable(),
  transaction_split: jsonSchema.optional(),
  trip_id: z.string().optional(),
});

export const publicTripTransactionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_transaction_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_transaction_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_transaction_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicUserNotificationRowSchema = z.object({
  created_at: z.string(),
  details: jsonSchema.nullable(),
  id: z.number(),
  read_at: z.string().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserNotificationInsertSchema = z.object({
  created_at: z.string(),
  details: jsonSchema.optional().nullable(),
  id: z.number().optional(),
  read_at: z.string().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserNotificationUpdateSchema = z.object({
  created_at: z.string().optional(),
  details: jsonSchema.optional().nullable(),
  id: z.number().optional(),
  read_at: z.string().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserNotificationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_notification_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("user_notification_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("user_notification_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicUserinfoRowSchema = z.object({
  avatarUrl: z.string().nullable(),
  firstName: z.string().nullable(),
  lastName: z.string().nullable(),
  userId: z.string(),
});

export const publicUserinfoInsertSchema = z.object({
  avatarUrl: z.string().optional().nullable(),
  firstName: z.string().optional().nullable(),
  lastName: z.string().optional().nullable(),
  userId: z.string(),
});

export const publicUserinfoUpdateSchema = z.object({
  avatarUrl: z.string().optional().nullable(),
  firstName: z.string().optional().nullable(),
  lastName: z.string().optional().nullable(),
  userId: z.string().optional(),
});

export const publicUserscoreRowSchema = z.object({
  createdAt: z.string(),
  gameId: z.string(),
  history: z.array(z.number()),
  updatedAt: z.string(),
  userId: z.string(),
});

export const publicUserscoreInsertSchema = z.object({
  createdAt: z.string().optional(),
  gameId: z.string(),
  history: z.array(z.number()).optional(),
  updatedAt: z.string().optional(),
  userId: z.string(),
});

export const publicUserscoreUpdateSchema = z.object({
  createdAt: z.string().optional(),
  gameId: z.string().optional(),
  history: z.array(z.number()).optional(),
  updatedAt: z.string().optional(),
  userId: z.string().optional(),
});

export const publicUserscoreRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("UserScore_userId_fkey1"),
    columns: z.tuple([z.literal("userId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("UserScore_userId_fkey1"),
    columns: z.tuple([z.literal("userId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("UserScore_userId_fkey1"),
    columns: z.tuple([z.literal("userId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicVAccommodationUnassignedTripParticipantsRowSchema = z.object(
  {
    avatar_url: z.string().nullable(),
    first_name: z.string().nullable(),
    group_member_id: z.string().nullable(),
    group_member_status: publicAccGroupUserStatusSchema.nullable(),
    id: z.string().nullable(),
    is_confirmed: z.boolean().nullable(),
    is_declined: z.boolean().nullable(),
    is_tentative: z.boolean().nullable(),
    last_name: z.string().nullable(),
    nickname: z.string().nullable(),
    role: publicTripParticipantRoleSchema.nullable(),
    status: publicTripParticipantStatusSchema.nullable(),
    trip_id: z.string().nullable(),
    user_id: z.string().nullable(),
  },
);

export const publicVAccommodationUnassignedTripParticipantsRelationshipsSchema =
  z.tuple([
    z.object({
      foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
      columns: z.tuple([z.literal("trip_id")]),
      isOneToOne: z.literal(false),
      referencedRelation: z.literal("trip"),
      referencedColumns: z.tuple([z.literal("id")]),
    }),
    z.object({
      foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
      columns: z.tuple([z.literal("trip_id")]),
      isOneToOne: z.literal(false),
      referencedRelation: z.literal("v_trip_details"),
      referencedColumns: z.tuple([z.literal("id")]),
    }),
    z.object({
      foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
      columns: z.tuple([z.literal("trip_id")]),
      isOneToOne: z.literal(false),
      referencedRelation: z.literal("v_trip_financial_summary"),
      referencedColumns: z.tuple([z.literal("trip_id")]),
    }),
  ]);

export const publicVGroupBalanceRowSchema = z.object({
  borrower: jsonSchema.nullable(),
  borrower_id: z.string().nullable(),
  currency_balance: jsonSchema.nullable(),
  group_id: z.string().nullable(),
  lender: jsonSchema.nullable(),
  lender_id: z.string().nullable(),
});

export const publicVGroupBalanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_paid_by_fkey"),
    columns: z.tuple([z.literal("lender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_split_borrower_id_fkey"),
    columns: z.tuple([z.literal("borrower_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
]);

export const publicVGroupDailyTransactionSummaryRowSchema = z.object({
  amount: z.number().nullable(),
  date: z.string().nullable(),
  group_id: z.string().nullable(),
  iso: z.string().nullable(),
  paid_by: jsonSchema.nullable(),
});

export const publicVGroupDailyTransactionSummaryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVGroupInvitationRowSchema = z.object({
  accepted_at: z.string().nullable(),
  created_at: z.string().nullable(),
  group: jsonSchema.nullable(),
  group_id: z.string().nullable(),
  group_member: jsonSchema.nullable(),
  group_member_id: z.string().nullable(),
  rejected_at: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const publicVGroupInvitationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_invitation_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_member"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_member_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_group_member_id_fkey"),
    columns: z.tuple([z.literal("group_member_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("group_member_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_invitation_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicVGroupMemberDetailsRowSchema = z.object({
  added_at: z.string().nullable(),
  assigned_at: z.string().nullable(),
  group_id: z.string().nullable(),
  id: z.string().nullable(),
  nickname: z.string().nullable(),
  removed_at: z.string().nullable(),
  status: publicAccGroupUserStatusSchema.nullable(),
  user: jsonSchema.nullable(),
  user_id: z.string().nullable(),
});

export const publicVGroupMemberDetailsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_member_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicVGroupMemberNetBalanceRowSchema = z.object({
  group_id: z.string().nullable(),
  iso: z.string().nullable(),
  member: jsonSchema.nullable(),
  net_amount: z.number().nullable(),
  owed_amount: z.number().nullable(),
  paid_amount: z.number().nullable(),
  status: z.string().nullable(),
});

export const publicVGroupMembershipRowSchema = z.object({
  archived_at: z.string().nullable(),
  created_at: z.string().nullable(),
  currencies: jsonSchema.nullable(),
  description: z.string().nullable(),
  id: z.string().nullable(),
  name: z.string().nullable(),
  owner_id: z.string().nullable(),
  thumbnail_url: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const publicVGroupMembershipRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("UserInfo"),
    referencedColumns: z.tuple([z.literal("userId")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal(
      "v_accommodation_unassigned_trip_participants",
    ),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_participant_details"),
    referencedColumns: z.tuple([z.literal("user_id")]),
  }),
]);

export const publicVGroupTotalSpendingRowSchema = z.object({
  amount: z.number().nullable(),
  group_id: z.string().nullable(),
  iso: z.string().nullable(),
});

export const publicVGroupTotalSpendingRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transaction_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVTripAccommodationSummaryRowSchema = z.object({
  accommodation_units: z.array(jsonSchema).nullable(),
  check_in_date: z.string().nullable(),
  check_out_date: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string().nullable(),
  name: z.string().nullable(),
  status: publicTripStatusSchema.nullable(),
  stay_duration_days: z.number().nullable(),
  trip_id: z.string().nullable(),
});

export const publicVTripAccommodationSummaryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("accommodation_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicVTripDetailsRowSchema = z.object({
  currency_iso_code: z.string().nullable(),
  description: z.string().nullable(),
  end_date: z.string().nullable(),
  group_id: z.string().nullable(),
  id: z.string().nullable(),
  location: z.string().nullable(),
  name: z.string().nullable(),
  participants: jsonSchema.nullable(),
  start_date: z.string().nullable(),
  status: publicTripStatusSchema.nullable(),
  text_document_id: z.string().nullable(),
  type: publicTripTypesSchema.nullable(),
});

export const publicVTripDetailsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_group_membership"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_text_document_id_fkey"),
    columns: z.tuple([z.literal("text_document_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("TextDocument"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVTripFinancialSummaryRowSchema = z.object({
  financials: jsonSchema.nullable(),
  financials_by_category: jsonSchema.nullable(),
  participants: jsonSchema.nullable(),
  trip_currency: z.string().nullable(),
  trip_id: z.string().nullable(),
});

export const publicVTripParticipantDetailsRowSchema = z.object({
  avatar_url: z.string().nullable(),
  first_name: z.string().nullable(),
  group_member_id: z.string().nullable(),
  group_member_status: publicAccGroupUserStatusSchema.nullable(),
  id: z.string().nullable(),
  is_confirmed: z.boolean().nullable(),
  is_declined: z.boolean().nullable(),
  is_tentative: z.boolean().nullable(),
  last_name: z.string().nullable(),
  nickname: z.string().nullable(),
  role: publicTripParticipantRoleSchema.nullable(),
  status: publicTripParticipantStatusSchema.nullable(),
  trip_id: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const publicVTripParticipantDetailsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("trip"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_details"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("trip_participant_trip_id_fkey"),
    columns: z.tuple([z.literal("trip_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("v_trip_financial_summary"),
    referencedColumns: z.tuple([z.literal("trip_id")]),
  }),
]);

export const publicAccGetTransactionCurrencyArgsSchema = z.object({
  p_transaction_id: z.string(),
});

export const publicAccGetTransactionCurrencyReturnsSchema = z.string();

export const publicAccRecalcGroupBalancePairArgsSchema = z.object({
  p_borrower_id: z.string(),
  p_group_id: z.string(),
  p_lender_id: z.string(),
});

export const publicAccRecalcGroupBalancePairReturnsSchema = z.undefined();

export const publicAccSendInvitationArgsSchema = z.object({
  p_group_id: z.string(),
  p_group_member_id: z.string(),
  p_user_id: z.string(),
});

export const publicAccSendInvitationReturnsSchema = z.undefined();

export const publicAccUpdateGroupBalanceArgsSchema = z.object({
  p_amount: z.number(),
  p_borrower_id: z.string(),
  p_group_id: z.string(),
  p_iso_code: z.string(),
  p_lender_id: z.string(),
});

export const publicAccUpdateGroupBalanceReturnsSchema = z.undefined();

export const publicAccUpsertTransactionWithSplitsArgsSchema = z.object({
  p_transaction: publicTransactionRowSchema,
  p_transaction_splits: z.array(publicTransactionSplitRowSchema),
});

export const publicAccUpsertTransactionWithSplitsReturnsSchema = z.string();

export const publicCheckTableRlsPermissionsArgsSchema = z.object({
  p_operations: z.array(z.string()).optional(),
  p_table_name: z.string(),
});

export const publicCheckTableRlsPermissionsReturnsSchema = jsonSchema;

export const publicCountAccommodationAssignmentsArgsSchema = z.object({
  p_accommodation_id: z.string(),
});

export const publicCountAccommodationAssignmentsReturnsSchema = z.number();

export const publicDbSetAuditMechanismArgsSchema = z.object({
  p_schema: z.string(),
  p_table: z.string(),
});

export const publicDbSetAuditMechanismReturnsSchema = z.undefined();

export const publicIsAccGroupMemberArgsSchema = z.object({
  p_group_id: z.string(),
});

export const publicIsAccGroupMemberReturnsSchema = z.boolean();

export const publicIsAccGroupOwnerArgsSchema = z.object({
  p_group_id: z.string(),
});

export const publicIsAccGroupOwnerReturnsSchema = z.boolean();

export const publicIsTripAdminArgsSchema = z.object({
  p_trip_id: z.string(),
});

export const publicIsTripAdminReturnsSchema = z.boolean();

export const publicIsTripCreatorArgsSchema = z.object({
  p_trip_id: z.string(),
});

export const publicIsTripCreatorReturnsSchema = z.boolean();

export const publicIsTripParticipantArgsSchema = z.object({
  p_trip_id: z.string(),
});

export const publicIsTripParticipantReturnsSchema = z.boolean();

export const publicRlsCreateAccommodationUnitArgsSchema = z.object({
  p_accommodation_id: z.string(),
});

export const publicRlsCreateAccommodationUnitReturnsSchema = z.boolean();

export const publicRlsDeleteAccommodationUnitArgsSchema = z.object({
  p_accommodation_id: z.string(),
});

export const publicRlsDeleteAccommodationUnitReturnsSchema = z.boolean();

export const publicRlsEditAccommodationUnitArgsSchema = z.object({
  p_accommodation_id: z.string(),
});

export const publicRlsEditAccommodationUnitReturnsSchema = z.boolean();

export const publicRlsModifyAccommodationUnitAssignmentArgsSchema = z.object({
  p_accommodation_unit_id: z.string(),
});

export const publicRlsModifyAccommodationUnitAssignmentReturnsSchema =
  z.boolean();

export const publicRlsReadAccommodationUnitArgsSchema = z.object({
  p_accommodation_id: z.string(),
});

export const publicRlsReadAccommodationUnitReturnsSchema = z.boolean();

export const publicRlsReadAccommodationUnitAssignmentArgsSchema = z.object({
  p_accommodation_unit_id: z.string(),
});

export const publicRlsReadAccommodationUnitAssignmentReturnsSchema =
  z.boolean();

export const publicSendNotificationArgsSchema = z.object({
  p_details: jsonSchema,
  p_title: z.string(),
  p_user_id: z.string(),
});

export const publicSendNotificationReturnsSchema = z.undefined();

export const publicTripInsertOwnerParticipantArgsSchema = z.object({
  p_group_id: z.string(),
  p_trip_id: z.string(),
});

export const publicTripInsertOwnerParticipantReturnsSchema = z.string();

export const publicTripTransactionCalculateTotalArgsSchema = z.object({
  p_calculation_type: publicTripTransactionCalculationTypeSchema,
  p_trip_id: z.string(),
  p_unit_amount: z.number(),
});

export const publicTripTransactionCalculateTotalReturnsSchema = z.number();
